site_name: Dart, I see you
site_description: wiki
site_author: vucre
nav:
    - Home: index.md
    - About: about.md
theme: windmill
repo_name: GitHub
repo_url: https://github.com/vucre/wiki.dart.icu
